name: Publish Artifactory Artifact

on:
  workflow_call:
    inputs:
      artifactory_url:
        description: 'The URL of the Artifactory server'
        required: true
        type: string
      repository:
        description: 'The Artifactory repository name'
        required: true
        type: string
      artifact_path:
        description: 'The local path to the artifact to be uploaded'
        required: true
        type: string
      target_path:
        description: 'The target path in the repository to upload the artifact'
        required: true
        type: string
      username:
        description: 'The username for Artifactory authentication'
        required: true
        type: string
      password:
        description: 'The password or API key for Artifactory authentication'
        required: true
        type: string
  workflow_dispatch:

jobs:
  publish-artifact:
    runs-on: self-hosted
    steps:
      - name: Checkout repository (if needed)
        uses: actions/checkout@v3

      - name: Publish artifact to Artifactory
        run: |
          curl -u "${{ inputs.username }}:${{ inputs.password }}" \
            -T "${{ inputs.artifact_path }}" \
            "${{ inputs.artifactory_url }}/${{ inputs.repository }}/${{ inputs.target_path }}"