name: "Run Unit Tests"

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
        description: "Java version to use"
  workflow_dispatch:
  inputs:
    test-pattern:
    required: false
    type: string
    description: "Pattern to specify which tests to run"
jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Build application
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew test

      - name: Inspect test results
        if: failure()
        run: |
          echo "Unit tests failed. Inspecting test results..."
          cat build/reports/tests/test/index.html