name: Execute Script

on:
  workflow_call:
    inputs:
      script_url:
        description: "URL of the .sh script to download and execute"
        required: true
        type: string
      script_args:
        description: "Arguments to pass to the script"
        required: false
        type: string
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Name of the repository containing the script"
        required: true
        default: "github-actions-snippets"
        type: string
      script_path:
        description: "Path to the script within the repository"
        required: true
        default: "src/scripts/script.sh"
        type: string

jobs:
  # This workflow contains a single job called "execute script"
  execute-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Execute script
        id: execute_script
        run: |
          script_path="./src/scripts"
          cd $script_path
          chmod +x script.sh
          script.sh ${{ inputs.script_args }}
        env:
          SCRIPT_ARGS: ${{ inputs.script_args }}

      - name: Check script execution
        if: ${{ failure() }}
        run: |
          echo "Script execution failed."
          exit 1

      - name: Set outputs
        id: set_outputs
        run: |
          echo "output_key=example_output" >> $GITHUB_OUTPUT
        env:
          OUTPUT_KEY: example_output
